### ISSUE TITLE
q2 protein-pca plot-loadings 

### ISSUE THREAD

**Issue by rytakahas** [bokulich-lab/q2-protein-pca#17]
Following the tutorial, I am not able to execute the last command;
q2 protein-pca plot-loadings --i-pca-loadings thioredoxin-pca-loadings.qza --i-positions-mapping thioredoxin-mapped.qza --o-visualization thioredoxin-pca-loadings.qzv

is this command q2-protein-pca? What I am missing?

thanks

**Comment by misialq** [comment]
Hi @rytakahas!
thanks for trying it out and posting here. The command should be `qiime protein-pca ...` and not `q2 protein-pca ...` - there is a mistake in the tutorial. Sorry for that, will fix!
